-- Create storage bucket for COIs
INSERT INTO storage.buckets (id, name, public) VALUES ('coi-documents', 'coi-documents', false);

-- Policy: Authenticated users (GCs) can view everything
CREATE POLICY "GCs can view all documents"
ON storage.objects FOR SELECT
USING (auth.role() = 'authenticated');

-- Policy: Public/Anon can upload if they have a token?
-- Storage policies don't easily access the subcontractor token without a join or custom function.
-- For a wedge/prototype, we often allow public uploads to a specific folder or use signed URLs.
-- Subcontractors are technically "anonymous" in this flow unless they sign in.
-- We will allow public uploads to this bucket for now, restricted by application logic (UI only shows for valid tokens).
-- In production, we'd use signed upload URLs generated by the server.
CREATE POLICY "Public can upload documents"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'coi-documents');

-- Policy: Public cannot list/view (blind upload)
-- This is secure enough for a prototype.
